services:
  terraform:
    platform: linux/amd64
    image: globalforestwatch/terraform:v0.13.3
    volumes:
      - ../../:/usr/local/src
      - $HOME/.aws:/root/.aws:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - ENV
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION=us-east-1
    working_dir: /usr/local/src
    entrypoint: infra
